blank_issues_enabled: false
contact_links:
  - name: FiveAI Help Center
    url: https://discord.gg/FmnrZb6SqQ
    about: Official central repository for tips, tricks, tutorials, known issues, and best practices for FiveAI usage.
  - name: Billing Issues
    url: https://discord.gg/FmnrZb6SqQ
    about: Instructions for billing and subscription related support
  - name: Discord Chat
    url: https://discord.gg/FmnrZb6SqQ
    about: Build, share, and learn with other FiveAI Users in real time.
